# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Build+Test CI

on:
  push:
    branches: [master, gh-actions]
    tags: [v*]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  make:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pyelftools python3-pip \
                                libcap-dev libseccomp-dev ninja-build
        sudo pip3 install meson
    - uses: actions/checkout@v2
    - run: |
        meson -Duse_libcap=enabled \
              -Duse_seccomp=true \
              -Dbuild_manpages=disabled \
              -Dtests=true \
              -Duse_fuzzing=true \
              build
        ninja -C build
        ninja -C build test

  build-macos:
    strategy:
      matrix:
        os: [macos-latest]
        cc: [clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - name: Install dependencies
      run: brew install meson ninja
    - uses: actions/checkout@v2
    - run: |
        meson -Duse_libcap=disabled \
              -Duse_seccomp=false \
              -Dbuild_manpages=disabled \
              -Dtests=true \
              -Duse_fuzzing=true \
              build
        ninja -C build
        # The unittests generally assume a Linux ELF host, so don't bother making
        # sure they pass on macOS.  Run them out of morbid curiosity I guess.
        ninja -kC build test ||:
